import './_style/globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from './Providers'
import Footer from './_components/common/footer/Footer'
import Header from './_components/common/header/Header'
import Feedback from './_components/common/feedback/Feedback'
import { GeneralContextProvider } from '@/context/context'

//font
const font = Inter({ subsets: ['latin'] })

//schema
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Product',
  name: 'Name',
  image: 'Image',
  description: 'Description',
}

//viewport
export const viewport = {
  themeColor: 'white',
}

//metadata
export const metadata = {
  title: {
    template: '%s | Key',
    default: 'Book Reviews | Key',
  },
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'Next.js',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'JavaScript'],
  authors: [{ name: 'Seb' }, { name: 'Josh', url: 'https://nextjs.org' }],
  creator: 'Jiachi Liu',
  publisher: 'Sebastian Markbåge',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://acme.com'),
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'it-IT': '/it-IT',
    },
  },
  icons: {
    icon: '/icon.png',
    apple: '/apple-icon.png',
  },
  robots: {
    index: false,
    follow: false,
    nocache: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
  openGraph: {
    title: 'Next.js',
    description: 'The React Framework for the Web',
    url: 'https://nextjs.org',
    siteName: 'Next.js',
    authors: ['Seb', 'Josh'],
    images: [
      {
        url: 'https://nextjs.org/og-alt.png', // Must be an absolute URL
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Next.js',
    description: 'The React Framework for the Web',
    siteId: '1467726470533754880',
    creator: '@nextjs',
    creatorId: '1467726470533754880',
    images: ['https://nextjs.org/og.png'], // Must be an absolute URL
  },
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id='body' className={font.className}>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <AuthProvider>
          <GeneralContextProvider>
            <Header />
            {children}
            <Feedback />
            <Footer />
          </GeneralContextProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
